 a =[ "air_conditiong",
      "kitchen",
      "internet",
      "tv",
      "cable_tv",
      "internet",
      "washer",
      "gym",
      "handicap_accessible",
      "smoking_allowed",
      "indoor_fireplace ",    
      "heating",
      "dryer",
      "wireless_internet",
      "elevator",
      "pets_allowed",
      "family_friendly",
      "shampoo",
      "essentials",
      "pool",
      "hot_tub",
      "smoke_detector", 
      "first_aid_kit",
      "carbon_monoxide_detector"]

puts a.sort